ssl_certificate     /etc/letsencrypt/live/sensio.mx/fullchain.pem;
ssl_certificate_key /etc/letsencrypt/live/sensio.mx/privkey.pem;
ssl_protocols       TLSv1.2 TLSv1.3;
ssl_ciphers         HIGH:!aNULL:!MD5;
