# Servidor de actualizaciones OTA (ESP32OTAPull) - ota.sensio.mx

server {
    listen 80;
    listen [::]:80;
    server_name ota.sensio.mx;

    include /etc/nginx/snippets/acme-redirect.conf;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name ota.sensio.mx;

    include /etc/nginx/snippets/ssl-sensio.conf;

    root /usr/share/nginx/ota;

    location / {
        autoindex off;
        try_files $uri =404;
    }
}
