# Landing page - sensio.mx / www.sensio.mx

server {
    listen 80;
    listen [::]:80;
    server_name sensio.mx www.sensio.mx;

    include /etc/nginx/snippets/acme-redirect.conf;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name sensio.mx www.sensio.mx;

    include /etc/nginx/snippets/ssl-sensio.conf;

    location / {
        proxy_pass http://landing:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
