[agent]
  interval = "10s"
  flush_interval = "10s"

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "${INFLUX_TOKEN}"
  organization = "${INFLUX_ORG}"
  bucket = "${INFLUX_BUCKET}"

[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = ["monitoreo/+"]
  data_format = "json_v2"
  name_override = "env_monitoring"

  [[inputs.mqtt_consumer.topic_parsing]]
    topic = "monitoreo/+"
    tags  = "_/device_id"

  [[inputs.mqtt_consumer.json_v2]]

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "metrics.CVOL"
      rename = "cvol"
      type = "float"
      optional = true

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "metrics.mq135_adc"
      rename = "mq135_adc"
      type = "int"
      optional = true

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "metadata.coord_x"
      rename = "lon"
      type = "float"
      optional = true

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "metadata.coord_y"
      rename = "lat"
      type = "float"
      optional = true

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "metadata.device.wifi.rssi"
      rename = "rssi"
      type = "int"
      optional = true

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "metadata.device.instruments.mq135_adc0"
      rename = "mq135_adc0"
      type = "int"
      optional = true

    [[inputs.mqtt_consumer.json_v2.tag]]
      path = "metadata.device.fw"
      rename = "fw"
      optional = true

    [[inputs.mqtt_consumer.json_v2.tag]]
      path = "metadata.device.instruments.mq135_cal"
      rename = "mq135_cal"
      optional = true
