apiVersion: 1

contactPoints:
  - orgId: 1
    name: telegram-servidor
    receivers:
      - uid: telegram-servidor-1
        type: telegram
        settings:
          bottoken: "${TELEGRAM_BOT_TOKEN}"
          chatid: "${TELEGRAM_CHAT_ID}"
          message: |
            {{ template "default.message" . }}
        disableResolveMessage: false
